
"""
POR REGISTRO

unpack[0] 64 -> Bytes que necesita TOD0 el registro
unpack[1] 15 -> Bytes de la parte del usuario
unpack[2.. inicio + 8] ... -> Datos del usuario: codigo, nombres... etc

si unpack[inicio + 9] no es null, entonces hay publicaciones (ej, en 12):
    unpack[12] 130 -> Bytes de la parte de la publicacion
    unpack[13.. inicio + 6] ... -> Datos de la publicacion: codigo, info...etc
    
    
    si unpack[inicio + 7] no es null, entonces hay comentarios (ej, en 20):
        unpack[20] 150 -> Bytes de la parte del comentario
        unpack[20.. inicio + 4 ] ... -> Datos del comentario: codigo, reaciones.. etc
        
        RECORRER EN UN BUCLE HASTA QUE LA POSICION ACTUAL DEL CURSOR SEA IGUAL AL TAMAÑO TOTAL DE LOS COMENTARIOS

    RECORRER EN UN BUCLE HASTA QUE LA POSICION ACTUAL DEL CURSOR SEA IGUAL AL TAMAÑO TOTAL DE LAS PUBLICACIONES

ALMACENAR USUARIO, PUBLICACIONES[] Y COMENTARIOS[] HASTA QUE LA POSICION ACTUAL DEL CURSOR SEA IGUAL AL TAMAÑO DE TOD0 EL REGISTRO 




EJ DE 1 REGISTRO:

TAMAÑO REGISTRO 1 | TAMAÑO USUARIO 1 | CODIGO USUARIO | lONG NOMBRE | NOMBRE DE USUARIO | FECHA | SEGUIDORES | SEGUIDOS | LONG BIO | BIO

TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 1 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO

TAMAÑO COMENTARIOS PUB 1 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO

"""


"""
VARIOS REGISTROS SERIAN ALGO ASÍ: 



TAMAÑO REGISTRO 2 | TAMAÑO USUARIO 2 | CODIGO USUARIO | lONG NOMBRE | NOMBRE DE USUARIO | FECHA | SEGUIDORES | SEGUIDOS | LONG BIO | BIO
    TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 2 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 2 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 3 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
    TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 3 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO 
        
        

TAMAÑO REGISTRO 3 | TAMAÑO USUARIO 3 | CODIGO USUARIO | lONG NOMBRE | NOMBRE DE USUARIO | FECHA | SEGUIDORES | SEGUIDOS | LONG BIO | BIO
    TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 1 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO
        TAMAÑO COMENTARIOS PUB 1 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
    TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 3 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
    TAMAÑO PUBLICACIONES | TAMAÑO PUBLICACION 3 | CODIGO PUBLICACION | FECHA PUBLICACION | REACCIONES | COMPARTIDOS | LONG CONTENIDO | CONTENIDO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
        TAMAÑO COMENTARIOS PUB 2 | TAMAÑO COMENTARIO 1 | REACCIONES | LONG INFO COMENTARIO | INFO COMENTARIO
"""